# Generated by Django 3.1 on 2020-08-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlemodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='categories',
            field=models.CharField(choices=[('fashedpdpion', 'fc nahion'), ('beauty', 'beauty')], default='fashion', max_length=50),
        ),
    ]
