# Generated by Django 3.1 on 2020-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200818_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='categories',
            field=models.CharField(choices=[('art & architecture', 'Art & Architecture'), ('boating & aviation', 'Boating & Aviation'), ('business & finance', 'Business & Finance'), ('cars & motorcycles', 'Cars & Motorcycles'), ('celebrity & gossip', 'Celebrity & Gossip'), ('comics & manga', 'Comics & Manga'), ('crafts', 'Crafts'), ('culture & literature', 'Culture & Literature'), ('family & parenting', 'Family & Parenting'), ('fashion', 'Fashion'), ('food & wine', 'Food & Wine'), ('health & fitness', 'Health & Fitness'), ('home & garden', 'Home & Garden'), ('hunting & fishing', 'Hunting & Fishing'), ('kids & teen', 'Kids & Teen'), ('luxury', 'Luxury'), ("men's lifestyle", "Men's Lifestyle"), ('movies, tv & music', 'Movies, Tv & Music'), ('news & politics', 'News & Politics'), ('Photography', 'Photography'), ('science & engineering', 'Science & Engineering'), ('sports', 'Sports'), ('tech & gaming', 'Tech & Gaming'), ('travel & outdoor', 'Travel & Outdoor'), ("women's lifestyle", "Women's Lifestyle"), ('adult +18', 'Adult +18')], default='fashion', max_length=50),
        ),
    ]
