# Generated by Django 3.1 on 2020-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200818_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='categories',
            field=models.CharField(choices=[('Art & Architecture', 'Art & Architecture'), ('Boating & Aviation', 'Boating & Aviation'), ('Business & Finance', 'Business & Finance'), ('Cars & Motorcycles', 'Cars & Motorcycles'), ('Celebrity & Gossip', 'Celebrity & Gossip'), ('Comics & Manga', 'Comics & Manga'), ('Crafts', 'Crafts'), ('Culture & Literature', 'Culture & Literature'), ('Family & Parenting', 'Family & Parenting'), ('Fashion', 'Fashion'), ('Food & Wine', 'Food & Wine'), ('Health & Fitness', 'Health & Fitness'), ('Home & Garden', 'Home & Garden'), ('Hunting & Fishing', 'Hunting & Fishing'), ('Kids & Teen', 'Kids & Teen'), ('Luxury', 'Luxury'), ("Men's Lifestyle", "Men's Lifestyle"), ('Movies, Tv & Music', 'Movies, Tv & Music'), ('News & Politics', 'News & Politics'), ('Photography', 'Photography'), ('Science & Engineering', 'Science & Engineering'), ('Sports', 'Sports'), ('Tech & Gaming', 'Tech & Gaming'), ('Travel & Outdoor', 'Travel & Outdoor'), ("Women's Lifestyle", "Women's Lifestyle"), ('Adult +18', 'Adult +18')], default='fashion', max_length=50),
        ),
    ]
